// Code generated by "stringer -type=ProjectType,Framework,Language,Database,UserInterface"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WebApp-0]
	_ = x[ClientServer-1]
	_ = x[Mobile-2]
	_ = x[Terminal-3]
}

const _ProjectType_name = "WebAppClientServerMobileTerminal"

var _ProjectType_index = [...]uint8{0, 6, 18, 24, 32}

func (i ProjectType) String() string {
	if i < 0 || i >= ProjectType(len(_ProjectType_index)-1) {
		return "ProjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProjectType_name[_ProjectType_index[i]:_ProjectType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[React-0]
	_ = x[ExpressJs-1]
	_ = x[NodeJS-2]
	_ = x[NextJS-3]
	_ = x[ReactRouter-4]
}

const _Framework_name = "ReactExpressJsNodeJSNextJSReactRouter"

var _Framework_index = [...]uint8{0, 5, 14, 20, 26, 37}

func (i Framework) String() string {
	if i < 0 || i >= Framework(len(_Framework_index)-1) {
		return "Framework(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Framework_name[_Framework_index[i]:_Framework_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[C-0]
	_ = x[Javascript-1]
	_ = x[Typescript-2]
	_ = x[Go-3]
	_ = x[CPlusPlus-4]
	_ = x[Java-5]
	_ = x[Swift-6]
	_ = x[Kotlin-7]
	_ = x[CSharp-8]
	_ = x[Jsx-9]
}

const _Language_name = "CJavascriptTypescriptGoCPlusPlusJavaSwiftKotlinCSharpJsx"

var _Language_index = [...]uint8{0, 1, 11, 21, 23, 32, 36, 41, 47, 53, 56}

func (i Language) String() string {
	if i < 0 || i >= Language(len(_Language_index)-1) {
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Language_name[_Language_index[i]:_Language_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MongoDB-0]
	_ = x[SQLite-1]
	_ = x[None-2]
}

const _Database_name = "MongoDBSQLiteNone"

var _Database_index = [...]uint8{0, 7, 13, 17}

func (i Database) String() string {
	if i < 0 || i >= Database(len(_Database_index)-1) {
		return "Database(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Database_name[_Database_index[i]:_Database_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Store-0]
	_ = x[Download-1]
	_ = x[Blog-2]
	_ = x[Landing-3]
}

const _UserInterface_name = "StoreDownloadBlogLanding"

var _UserInterface_index = [...]uint8{0, 5, 13, 17, 24}

func (i UserInterface) String() string {
	if i < 0 || i >= UserInterface(len(_UserInterface_index)-1) {
		return "UserInterface(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserInterface_name[_UserInterface_index[i]:_UserInterface_index[i+1]]
}
