// Code generated by "stringer -type=UserInterface"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Store-0]
	_ = x[Download-1]
	_ = x[Blog-2]
	_ = x[Landing-3]
}

const _UserInterface_name = "StoreDownloadBlogEmpty"

var _UserInterface_index = [...]uint8{0, 5, 13, 17, 22}

func (i UserInterface) String() string {
	if i < 0 || i >= UserInterface(len(_UserInterface_index)-1) {
		return "UserInterface(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserInterface_name[_UserInterface_index[i]:_UserInterface_index[i+1]]
}
